INSERT INTO country(name) VALUES('Afghanistan');
INSERT INTO country(name) VALUES('Ã…landIslands');
INSERT INTO country(name) VALUES('Albania');
INSERT INTO country(name) VALUES('Algeria');
INSERT INTO country(name) VALUES('AmericanSamoa');
INSERT INTO country(name) VALUES('Andorra');
INSERT INTO country(name) VALUES('Angola');
INSERT INTO country(name) VALUES('Anguilla');
INSERT INTO country(name) VALUES('Antarctica');
INSERT INTO country(name) VALUES('Antiguaand Barbuda');
INSERT INTO country(name) VALUES('Argentina');
INSERT INTO country(name) VALUES('Armenia');
INSERT INTO country(name) VALUES('Aruba');
INSERT INTO country(name) VALUES('Australia');
INSERT INTO country(name) VALUES('Austria');
INSERT INTO country(name) VALUES('Azerbaijan');
INSERT INTO country(name) VALUES('Bahamas');
INSERT INTO country(name) VALUES('Bahrain');
INSERT INTO country(name) VALUES('Bangladesh');
INSERT INTO country(name) VALUES('Barbados');
INSERT INTO country(name) VALUES('Belarus');
INSERT INTO country(name) VALUES('Belgium');
INSERT INTO country(name) VALUES('Belize');
INSERT INTO country(name) VALUES('Benin');
INSERT INTO country(name) VALUES('Bermuda');
INSERT INTO country(name) VALUES('Bhutan');
INSERT INTO country(name) VALUES('Plurinational State of Bolivia');
INSERT INTO country(name) VALUES('Sint Eustatius and Saba Bonaire');
INSERT INTO country(name) VALUES('Bosniaand Herzegovina');
INSERT INTO country(name) VALUES('Botswana');
INSERT INTO country(name) VALUES('BouvetIsland');
INSERT INTO country(name) VALUES('Brazil');
INSERT INTO country(name) VALUES('BritishIndian Ocean Territory');
INSERT INTO country(name) VALUES('BruneiDarussalam');
INSERT INTO country(name) VALUES('Bulgaria');
INSERT INTO country(name) VALUES('BurkinaFaso');
INSERT INTO country(name) VALUES('Burundi');
INSERT INTO country(name) VALUES('Cambodia');
INSERT INTO country(name) VALUES('Cameroon');
INSERT INTO country(name) VALUES('Canada');
INSERT INTO country(name) VALUES('CapeVerde');
INSERT INTO country(name) VALUES('CaymanIslands');
INSERT INTO country(name) VALUES('CentralAfrican Republic');
INSERT INTO country(name) VALUES('Chad');
INSERT INTO country(name) VALUES('Chile');
INSERT INTO country(name) VALUES('China');
INSERT INTO country(name) VALUES('ChristmasIsland');
INSERT INTO country(name) VALUES('Cocos(Keeling) Islands');
INSERT INTO country(name) VALUES('Colombia');
INSERT INTO country(name) VALUES('Comoros');
INSERT INTO country(name) VALUES('Congo');
INSERT INTO country(name) VALUES('The Democratic Republic of the Congo');
INSERT INTO country(name) VALUES('CookIslands');
INSERT INTO country(name) VALUES('CostaRica');
INSERT INTO country(name) VALUES('Côte d Ivoire');
INSERT INTO country(name) VALUES('Croatia');
INSERT INTO country(name) VALUES('Cuba');
INSERT INTO country(name) VALUES('Curaçao');
INSERT INTO country(name) VALUES('Cyprus');
INSERT INTO country(name) VALUES('CzechRepublic');
INSERT INTO country(name) VALUES('Denmark');
INSERT INTO country(name) VALUES('Djibouti');
INSERT INTO country(name) VALUES('Dominica');
INSERT INTO country(name) VALUES('DominicanRepublic');
INSERT INTO country(name) VALUES('Ecuador');
INSERT INTO country(name) VALUES('Egypt');
INSERT INTO country(name) VALUES('ElSalvador');
INSERT INTO country(name) VALUES('EquatorialGuinea');
INSERT INTO country(name) VALUES('Eritrea');
INSERT INTO country(name) VALUES('Estonia');
INSERT INTO country(name) VALUES('Ethiopia');
INSERT INTO country(name) VALUES('FalklandIslands (Malvinas)');
INSERT INTO country(name) VALUES('FaroeIslands');
INSERT INTO country(name) VALUES('Fiji');
INSERT INTO country(name) VALUES('Finland');
INSERT INTO country(name) VALUES('France');
INSERT INTO country(name) VALUES('FrenchGuiana');
INSERT INTO country(name) VALUES('FrenchPolynesia');
INSERT INTO country(name) VALUES('FrenchSouthern Territories');
INSERT INTO country(name) VALUES('Gabon');
INSERT INTO country(name) VALUES('Gambia');
INSERT INTO country(name) VALUES('Georgia');
INSERT INTO country(name) VALUES('Germany');
INSERT INTO country(name) VALUES('Ghana');
INSERT INTO country(name) VALUES('Gibraltar');
INSERT INTO country(name) VALUES('Greece');
INSERT INTO country(name) VALUES('Greenland');
INSERT INTO country(name) VALUES('Grenada');
INSERT INTO country(name) VALUES('Guadeloupe');
INSERT INTO country(name) VALUES('Guam');
INSERT INTO country(name) VALUES('Guatemala');
INSERT INTO country(name) VALUES('Guernsey');
INSERT INTO country(name) VALUES('Guinea');
INSERT INTO country(name) VALUES('Guinea-Bissau');
INSERT INTO country(name) VALUES('Guyana');
INSERT INTO country(name) VALUES('Haiti');
INSERT INTO country(name) VALUES('HeardIsland and McDonald Islands');
INSERT INTO country(name) VALUES('HolySee (Vatican City State)');
INSERT INTO country(name) VALUES('Honduras');
INSERT INTO country(name) VALUES('HongKong');
INSERT INTO country(name) VALUES('Hungary');
INSERT INTO country(name) VALUES('Iceland');
INSERT INTO country(name) VALUES('India');
INSERT INTO country(name) VALUES('Indonesia');
INSERT INTO country(name) VALUES('Islamic Republic of Iran');
INSERT INTO country(name) VALUES('Iraq');
INSERT INTO country(name) VALUES('Ireland');
INSERT INTO country(name) VALUES('Isleof Man');
INSERT INTO country(name) VALUES('Israel');
INSERT INTO country(name) VALUES('Italy');
INSERT INTO country(name) VALUES('Jamaica');
INSERT INTO country(name) VALUES('Japan');
INSERT INTO country(name) VALUES('Jersey');
INSERT INTO country(name) VALUES('Jordan');
INSERT INTO country(name) VALUES('Kazakhstan');
INSERT INTO country(name) VALUES('Kenya');
INSERT INTO country(name) VALUES('Kiribati');
INSERT INTO country(name) VALUES('Democratic People's Republic of Korea');
INSERT INTO country(name) VALUES('Republic of Korea');
INSERT INTO country(name) VALUES('Kuwait');
INSERT INTO country(name) VALUES('Kyrgyzstan');
INSERT INTO country(name) VALUES('LaoPeople's Democratic Republic');
INSERT INTO country(name) VALUES('Latvia');
INSERT INTO country(name) VALUES('Lebanon');
INSERT INTO country(name) VALUES('Lesotho');
INSERT INTO country(name) VALUES('Liberia');
INSERT INTO country(name) VALUES('Libya');
INSERT INTO country(name) VALUES('Liechtenstein');
INSERT INTO country(name) VALUES('Lithuania');
INSERT INTO country(name) VALUES('Luxembourg');
INSERT INTO country(name) VALUES('Macao');
INSERT INTO country(name) VALUES('the Former Yugoslav Republic of Macedonia');
INSERT INTO country(name) VALUES('Madagascar');
INSERT INTO country(name) VALUES('Malawi');
INSERT INTO country(name) VALUES('Malaysia');
INSERT INTO country(name) VALUES('Maldives');
INSERT INTO country(name) VALUES('Mali');
INSERT INTO country(name) VALUES('Malta');
INSERT INTO country(name) VALUES('MarshallIslands');
INSERT INTO country(name) VALUES('Martinique');
INSERT INTO country(name) VALUES('Mauritania');
INSERT INTO country(name) VALUES('Mauritius');
INSERT INTO country(name) VALUES('Mayotte');
INSERT INTO country(name) VALUES('Mexico');
INSERT INTO country(name) VALUES('Federated States of Micronesia');
INSERT INTO country(name) VALUES('Republic of Moldova');
INSERT INTO country(name) VALUES('Monaco');
INSERT INTO country(name) VALUES('Mongolia');
INSERT INTO country(name) VALUES('Montenegro');
INSERT INTO country(name) VALUES('Montserrat');
INSERT INTO country(name) VALUES('Morocco');
INSERT INTO country(name) VALUES('Mozambique');
INSERT INTO country(name) VALUES('Myanmar');
INSERT INTO country(name) VALUES('Namibia');
INSERT INTO country(name) VALUES('Nauru');
INSERT INTO country(name) VALUES('Nepal');
INSERT INTO country(name) VALUES('Netherlands');
INSERT INTO country(name) VALUES('NewCaledonia');
INSERT INTO country(name) VALUES('NewZealand');
INSERT INTO country(name) VALUES('Nicaragua');
INSERT INTO country(name) VALUES('Niger');
INSERT INTO country(name) VALUES('Nigeria');
INSERT INTO country(name) VALUES('Niue');
INSERT INTO country(name) VALUES('NorfolkIsland');
INSERT INTO country(name) VALUES('NorthernMariana Islands');
INSERT INTO country(name) VALUES('Norway');
INSERT INTO country(name) VALUES('Oman');
INSERT INTO country(name) VALUES('Pakistan');
INSERT INTO country(name) VALUES('Palau');
INSERT INTO country(name) VALUES('State of Palestine');
INSERT INTO country(name) VALUES('Panama');
INSERT INTO country(name) VALUES('PapuaNew Guinea');
INSERT INTO country(name) VALUES('Paraguay');
INSERT INTO country(name) VALUES('Peru');
INSERT INTO country(name) VALUES('Philippines');
INSERT INTO country(name) VALUES('Pitcairn');
INSERT INTO country(name) VALUES('Poland');
INSERT INTO country(name) VALUES('Portugal');
INSERT INTO country(name) VALUES('PuertoRico');
INSERT INTO country(name) VALUES('Qatar');
INSERT INTO country(name) VALUES('RÃ©union');
INSERT INTO country(name) VALUES('Romania');
INSERT INTO country(name) VALUES('RussianFederation');
INSERT INTO country(name) VALUES('Rwanda');
INSERT INTO country(name) VALUES('SaintBarthÃ©lemy');
INSERT INTO country(name) VALUES('Ascension and Tristan da Cunha Saint Helena');
INSERT INTO country(name) VALUES('SaintKitts and Nevis');
INSERT INTO country(name) VALUES('SaintLucia');
INSERT INTO country(name) VALUES('SaintMartin (French part)');
INSERT INTO country(name) VALUES('SaintPierre and Miquelon');
INSERT INTO country(name) VALUES('SaintVincent and the Grenadines');
INSERT INTO country(name) VALUES('Samoa');
INSERT INTO country(name) VALUES('SanMarino');
INSERT INTO country(name) VALUES('SaoTome and Principe');
INSERT INTO country(name) VALUES('SaudiArabia');
INSERT INTO country(name) VALUES('Senegal');
INSERT INTO country(name) VALUES('Serbia');
INSERT INTO country(name) VALUES('Seychelles');
INSERT INTO country(name) VALUES('SierraLeone');
INSERT INTO country(name) VALUES('Singapore');
INSERT INTO country(name) VALUES('SintMaarten (Dutch part)');
INSERT INTO country(name) VALUES('Slovakia');
INSERT INTO country(name) VALUES('Slovenia');
INSERT INTO country(name) VALUES('SolomonIslands');
INSERT INTO country(name) VALUES('Somalia');
INSERT INTO country(name) VALUES('SouthAfrica');
INSERT INTO country(name) VALUES('SouthGeorgia and the South Sandwich Islands');
INSERT INTO country(name) VALUES('SouthSudan');
INSERT INTO country(name) VALUES('Spain');
INSERT INTO country(name) VALUES('SriLanka');
INSERT INTO country(name) VALUES('Sudan');
INSERT INTO country(name) VALUES('Suriname');
INSERT INTO country(name) VALUES('Svalbardand Jan Mayen');
INSERT INTO country(name) VALUES('Swaziland');
INSERT INTO country(name) VALUES('Sweden');
INSERT INTO country(name) VALUES('Switzerland');
INSERT INTO country(name) VALUES('SyrianArab Republic');
INSERT INTO country(name) VALUES('Province of China Taiwan');
INSERT INTO country(name) VALUES('Tajikistan');
INSERT INTO country(name) VALUES('United Republic of Tanzania');
INSERT INTO country(name) VALUES('Thailand');
INSERT INTO country(name) VALUES('Timor-Leste');
INSERT INTO country(name) VALUES('Togo');
INSERT INTO country(name) VALUES('Tokelau');
INSERT INTO country(name) VALUES('Tonga');
INSERT INTO country(name) VALUES('Trinidadand Tobago');
INSERT INTO country(name) VALUES('Tunisia');
INSERT INTO country(name) VALUES('Turkey');
INSERT INTO country(name) VALUES('Turkmenistan');
INSERT INTO country(name) VALUES('Turksand Caicos Islands');
INSERT INTO country(name) VALUES('Tuvalu');
INSERT INTO country(name) VALUES('Uganda');
INSERT INTO country(name) VALUES('Ukraine');
INSERT INTO country(name) VALUES('UnitedArab Emirates');
INSERT INTO country(name) VALUES('UnitedKingdom');
INSERT INTO country(name) VALUES('UnitedStates');
INSERT INTO country(name) VALUES('UnitedStates Minor Outlying Islands');
INSERT INTO country(name) VALUES('Uruguay');
INSERT INTO country(name) VALUES('Uzbekistan');
INSERT INTO country(name) VALUES('Vanuatu');
INSERT INTO country(name) VALUES('Bolivarian Republic of Venezuela');
INSERT INTO country(name) VALUES('VietNam');
INSERT INTO country(name) VALUES('British Virgin Islands');
INSERT INTO country(name) VALUES('VirginIslands');
INSERT INTO country(name) VALUES('Wallisand Futuna');
INSERT INTO country(name) VALUES('WesternSahara');
INSERT INTO country(name) VALUES('Yemen');
INSERT INTO country(name) VALUES('Zambia');
INSERT INTO country(name) VALUES('Zimbabwe');